# .github/workflows/continuous-integration.yml

name: "Continuous integration"

on:
  
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:
  
  install:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: "Cache node_modules"
        uses: actions/cache@v1
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-
        env:
          YARN_CACHE_DIR: ~/.cache/yarn
      
      - name: "Install dependencies"
        run: |
          yarn install --frozen-lockfile
        env:
          YARN_CACHE_DIR: ~/.cache/yarn
      
      - name: "Apply patches"
        run: |
          yarn patch
  
  lint:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    needs:
      - install
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: "Install dependencies"
        run: |
          yarn install --frozen-lockfile
        env:
          YARN_CACHE_DIR: ~/.cache/yarn
      
      - name: "Apply patches"
        run: |
          yarn patch
      
      - name: "Check for lint"
        run: |
          yarn lint
  
  test:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    needs:
      - install
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: "Install dependencies"
        run: |
          yarn install --frozen-lockfile
        env:
          YARN_CACHE_DIR: ~/.cache/yarn
      
      - name: "Apply patches"
        run: |
          yarn patch
      
      - name: "Run tests"
        run: |
          yarn test
  
  build:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    needs:
      - install
      - lint
      - test
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: "Install dependencies"
        run: |
          yarn install --frozen-lockfile
        env:
          YARN_CACHE_DIR: ~/.cache/yarn
      
      - name: "Apply patches"
        run: |
          yarn patch
      
      - name: "Build"
        run: |
          yarn build
