# .github/workflows/continuous-integration.yml

name: "Continuous integration"

on:
  
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:
  
  install:
    name: "Install"
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v1
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
  lint:
    name: "Lint"
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    needs:
      - install
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v1
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
  test:
    name: "Test"
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    needs:
      - install
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v1
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    needs:
      - install
      - lint
      - test
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v1
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
