# .github/workflows/deployment.yml

name: "Deployment"

on:
  
  release:
    types: [ created ]

jobs:
  
  deploy:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        os: [ ubuntu-latest ]
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v2
