# .github/workflows/deployment.yml

name: "Deployment"

on:
  
  release:
    types: [ created ]

jobs:
  
  deploy:
    name: "Deploy"
    runs-on: ${{ matrix.os }}
    
    strategy:
      
      matrix:
        node-version: [ 12.0.0 ]
        os: [ ubuntu-latest ]
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v1
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
